#!/usr/bin/env python3
import argparse
import sys
from src.interface.main import main as interface_main
from src.core.knowledge_service import KnowledgeService

def main():
    parser = argparse.ArgumentParser(description='Knowledge repository')
    parser.add_argument(
        '-l',
        '--list',
        help='writes list of all knowledge to stdout',
        action='store_true'
    )
    args = parser.parse_args()

    if args.list:
        knowledge_service = KnowledgeService()
        knowledge = knowledge_service.list_knowledge()
        for item in knowledge:
            sys.stdout.write(f'title: {item.title}\n')
            sys.stdout.write(f'category: {item.category}\n')
            sys.stdout.write(f'created: {item.created}\n')
            sys.stdout.write(f'content: {item.content}\n')
            sys.stdout.write('\n')
    else:
        interface_main()

if __name__ == '__main__':
    main()

